# Copyright (c) 2025 nomike Postmann <nomike@nomike.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

---

ecdk-files:
  - '*.json'

rules:
  region-missing: enable
  region-invalid: enable
  region-stackname-mismatch:
    level: warning
  stack-module-missing: enable
  stack-class-missing: enable
  parameters-missing: enable
  stackname-too-long: enable
  stackname-doesnt-match-module-and-class:
    level: warning
  json5-file-extension-deprecated:
    level: warning
  region-mismatch-stack-tags:
    level: warning
  # anchors: enable
  # braces: enable
  # brackets: enable
  # colons: enable
  # commas: enable
  # comments:
  #   level: warning
  # comments-indentation:
  #   level: warning
  # document-end: disable
  # document-start:
  #   level: warning
  # empty-lines: enable
  # empty-values: disable
  # float-values: disable
  # hyphens: enable
  # indentation: enable
  # key-duplicates: enable
  # key-ordering: disable
  # line-length: enable
  # new-line-at-end-of-file: enable
  # new-lines: enable
  # octal-values: disable
  # quoted-strings: disable
  # trailing-spaces: enable
  # truthy:
  #   level: warning
